package agenciafiscalpresentacion;

import Control.ControlPresentacion;
import consultas.ConsultasLicencias;
import consultas.ConsultasPlacas;
import consultas.IConsultasLicencias;
import consultas.IConsultasPlacas;
import dtos.LicenciaDTO;
import dtos.PlacasDTO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class DlgHistorial extends javax.swing.JFrame {

    ControlPresentacion control = new ControlPresentacion();
    private DefaultTableModel modeloTabla1;
    private DefaultTableModel modeloTabla2;
    List<LicenciaDTO> listaLicencias;
    IConsultasLicencias lic;
    List<PlacasDTO> listaPlacas;
    IConsultasPlacas pla;
    String rfcPersona;

    /**
     * Creates new form FrmOpcionesCliente
     * @param rfc
     */
    public DlgHistorial(String rfc) {
        lic = new ConsultasLicencias();
        pla=new ConsultasPlacas();
        rfcPersona=rfc;
        initComponents();
        this.setVisible(true);
        importarTablaLicencias();
        importarTablaPlacas();
    }

    public void importarTablaLicencias() {
        modeloTabla1 = (DefaultTableModel) TbLicencia.getModel();
        listaLicencias = lic.listaLicencias(rfcPersona);
        for (LicenciaDTO l : listaLicencias) {
            insertarFilaLicencias(l);
        }
}
      public void importarTablaPlacas() {
      modeloTabla2 = (DefaultTableModel) TbPlacas.getModel();
 listaPlacas =pla.listaPlacas(rfcPersona) ;
        for (PlacasDTO p : listaPlacas) {
            insertarFilaPlacas(p);
        }
}
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOpciones = new javax.swing.JPanel();
        lblTituloSeccion = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lblOpciones1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbLicencia = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbPlacas = new javax.swing.JTable();
        lblOpciones2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelOpciones.setBackground(new java.awt.Color(204, 255, 204));
        panelOpciones.setPreferredSize(new java.awt.Dimension(520, 520));
        panelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloSeccion.setFont(new java.awt.Font("Amazon Ember", 1, 48)); // NOI18N
        lblTituloSeccion.setForeground(new java.awt.Color(64, 53, 44));
        lblTituloSeccion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSeccion.setText("Historial");
        panelOpciones.add(lblTituloSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 750, -1));

        btnCancelar.setBackground(new java.awt.Color(64, 53, 44));
        btnCancelar.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Regeresar");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusable(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelOpciones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 160, 50));

        btnSalir.setBackground(new java.awt.Color(64, 53, 44));
        btnSalir.setFont(new java.awt.Font("Amazon Ember", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelOpciones.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 160, 50));

        lblOpciones1.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblOpciones1.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones1.setText("Placas");
        panelOpciones.add(lblOpciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        TbLicencia.setBackground(new java.awt.Color(132, 203, 132));
        TbLicencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Rfc", "Vencimiento", "Vigencia", "Tipo", "Activa"
            }
        ));
        jScrollPane2.setViewportView(TbLicencia);

        panelOpciones.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 740, 140));

        TbPlacas.setBackground(new java.awt.Color(132, 203, 132));
        TbPlacas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FechaEmision", "FechaRecepcion", "Costo", "Id_Automovil"
            }
        ));
        jScrollPane3.setViewportView(TbPlacas);

        panelOpciones.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 740, 130));

        lblOpciones2.setFont(new java.awt.Font("Amazon Ember", 0, 36)); // NOI18N
        lblOpciones2.setForeground(new java.awt.Color(64, 53, 44));
        lblOpciones2.setText("Licencias");
        panelOpciones.add(lblOpciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        getContentPane().add(panelOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
  control.desplegarMenu();
  dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        control.desplegarDlgConsultas();
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed
private void insertarFilaLicencias(LicenciaDTO l) {
        Object[] fila = {
            l.getId(),
            l.getRFC(),
            l.getFv(),
            l.getVigencia(),
            l.getTipo(),
            l.isActiva()
        };
        modeloTabla1.addRow(fila);
    }


private void insertarFilaPlacas(PlacasDTO p) {
        Object[] fila = {
            p.getNumeroPlacas(),
            p.getFechaE(),
            p.getFechaR(),
            p.getCosto(),
            p.getIdAuto(),
            p.isActiva()
        };
        modeloTabla2.addRow(fila);
    }
        
         
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbLicencia;
    private javax.swing.JTable TbPlacas;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblOpciones1;
    private javax.swing.JLabel lblOpciones2;
    private javax.swing.JLabel lblTituloSeccion;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables

    
    

    

}
