package agenciafiscalpresentacion;

import Control.ControlPresentacion;
import consultas.ConsultasPlacas;
import consultas.IConsultasPlacas;
import dtos.AutomovilesDTO;
import dtos.PlacasDTO;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author molin
 */
public class DlgPlacasUsadas extends javax.swing.JDialog {

    ControlPresentacion control = new ControlPresentacion();
    public String rfcUsadas;
    IConsultasPlacas placasC;

    /**
     * Creates new form DlgPlacasUsadas
     *
     * @param parent
     * @param modal
     */
    public DlgPlacasUsadas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgPlacasUsadas() {
        initComponents();
        placasC = new ConsultasPlacas();
        if (rfcUsadas != null) {
            txtNumPlacas.setText(rfcUsadas);
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNumPlacas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtImportePlacasR = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        BotonRegreso = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtplacasN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PLACAS USADAS");

        jPanel1.setBackground(new java.awt.Color(235, 250, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(159, 224, 159));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("DATOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Numero de Nuevas placas:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 160, -1));

        txtNumPlacas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumPlacasKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumPlacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 190, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Importe:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));
        jPanel2.add(txtImportePlacasR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 110, -1));

        btnAceptar.setBackground(new java.awt.Color(153, 255, 102));
        btnAceptar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 130, 40));

        BotonRegreso.setBackground(new java.awt.Color(153, 255, 102));
        BotonRegreso.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonRegreso.setText("Volver");
        BotonRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresoActionPerformed(evt);
            }
        });
        jPanel2.add(BotonRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Numero de Anteriores:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 160, -1));

        txtplacasN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtplacasNKeyTyped(evt);
            }
        });
        jPanel2.add(txtplacasN, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 190, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 590, 390));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setText("PLACAS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        AutomovilesDTO autoBuscado;
        Float importe = 1000f;
        txtImportePlacasR.setText(String.valueOf(importe));
        autoBuscado = placasC.BuscarPlacas(txtNumPlacas.getText());
        if (autoBuscado != null) {
            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea agregar una placa nueva y cancelar las anteriores ?", "Pasar a placa usada", JOptionPane.YES_NO_OPTION);
            if (confirmacion == 0) {
                LocalDate localDate = LocalDate.now();
                //pasando la fecha localdate a date
                Date fechaEmision = java.util.Date.from(localDate.atStartOfDay().atZone(java.time.ZoneId.systemDefault()).toInstant());
                placasC.actualizarPlacas(autoBuscado.getIdAuto(), fechaEmision, false);
                PlacasDTO p = new PlacasDTO(txtplacasN.getText(),fechaEmision , null, importe, autoBuscado, true);
                placasC.AgregarPlacasUsadas(p,autoBuscado.getNumeroSerie());
                JOptionPane.showMessageDialog(this, "Placas y automovil agregados con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
            }
        }else{
        JOptionPane.showMessageDialog(this, "Este automovil no existe ", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void BotonRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresoActionPerformed
        // TODO add your handling code here:
        control.desplegarMenu();
        dispose();

    }//GEN-LAST:event_BotonRegresoActionPerformed

    private void txtNumPlacasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumPlacasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        String currentText = txtNumPlacas.getText();

        // Permite borrar cualquier carácter
        if (c == '\b') {
            return;
        }

        // Solo permite escribir letras y guión si hay menos de 3 letras
        if (currentText.length() < 3 && Character.isLetter(c)) {
            return;
        }

        // Permitir guión solo si hay 3 letras y no hay guión aún
        if (currentText.length() == 3 && c == '-' && !currentText.contains("-")) {
            return;
        }

        // Solo permite escribir dígitos si ya hay 4 caracteres (3 letras + 1 guión)
        if (currentText.length() == 4 && Character.isDigit(c)) {
            return;
        }

        // Solo permite escribir 3 dígitos después del guión
        if (currentText.length() > 4 && Character.isDigit(c)) {
            String digits = currentText.substring(5);
            if (digits.length() < 3) {
                return;
            }
        }

        evt.consume(); // Si no cumple ninguna de las condiciones, consume el evento

    }//GEN-LAST:event_txtNumPlacasKeyTyped

    private void txtplacasNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtplacasNKeyTyped
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        String currentText = txtplacasN.getText();

        // Permite borrar cualquier carácter
        if (c == '\b') {
            return;
        }

        // Solo permite escribir letras y guión si hay menos de 3 letras
        if (currentText.length() < 3 && Character.isLetter(c)) {
            return;
        }

        // Permitir guión solo si hay 3 letras y no hay guión aún
        if (currentText.length() == 3 && c == '-' && !currentText.contains("-")) {
            return;
        }

        // Solo permite escribir dígitos si ya hay 4 caracteres (3 letras + 1 guión)
        if (currentText.length() == 4 && Character.isDigit(c)) {
            return;
        }

        // Solo permite escribir 3 dígitos después del guión
        if (currentText.length() > 4 && Character.isDigit(c)) {
            String digits = currentText.substring(5);
            if (digits.length() < 3) {
                return;
            }
        }

        evt.consume();
    }//GEN-LAST:event_txtplacasNKeyTyped
    public void limpiar() {
        txtNumPlacas.setText("");
        txtImportePlacasR.setText("");
        txtplacasN.setText("");

    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgPlacasUsadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgPlacasUsadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgPlacasUsadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgPlacasUsadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgPlacasUsadas dialog = new DlgPlacasUsadas(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegreso;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtImportePlacasR;
    private javax.swing.JTextField txtNumPlacas;
    private javax.swing.JTextField txtplacasN;
    // End of variables declaration//GEN-END:variables
}
