package agenciafiscalpresentacion;

import Control.ControlPresentacion;
import Encriptacion.EncriptacionDatos;
import consultas.ConsultasPersonas;
import consultas.IConsultasPersonas;
import dtos.PersonasDTO;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author molin
 */
public class DlgRegistro extends javax.swing.JDialog {

    ControlPresentacion control = new ControlPresentacion();
    IConsultasPersonas personaConsulta;

    /**
     * Creates new form DlgRegistro
     *
     * @param parent
     * @param modal
     */
    public DlgRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        
    }

    public DlgRegistro() {
        initComponents();
        personaConsulta = new ConsultasPersonas();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        campoRFC = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoApellidoP = new javax.swing.JTextField();
        campoApellidoM = new javax.swing.JTextField();
        campoTelefono = new javax.swing.JTextField();
        BotonRegistro = new javax.swing.JButton();
        BotonRegistro1 = new javax.swing.JButton();
        campoCurp = new javax.swing.JTextField();
        BotonLimpiar = new javax.swing.JButton();
        BotonRegreso1 = new javax.swing.JButton();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRO");

        jPanel1.setBackground(new java.awt.Color(235, 250, 239));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        campoRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRFCKeyTyped(evt);
            }
        });
        jPanel1.add(campoRFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 219, -1));

        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });
        jPanel1.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 219, -1));

        campoApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoPKeyTyped(evt);
            }
        });
        jPanel1.add(campoApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 219, -1));

        campoApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoMKeyTyped(evt);
            }
        });
        jPanel1.add(campoApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 219, -1));

        campoTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 219, -1));

        BotonRegistro.setOpaque(false);
        BotonRegistro.setContentAreaFilled(false);
        BotonRegistro.setBorderPainted(false);
        BotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 160, 50));

        BotonRegistro1.setOpaque(false);
        BotonRegistro1.setContentAreaFilled(false);
        BotonRegistro1.setBorderPainted(false);
        BotonRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistro1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 160, 50));

        campoCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCurpKeyTyped(evt);
            }
        });
        jPanel1.add(campoCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 220, -1));

        BotonLimpiar.setOpaque(false);
        BotonLimpiar.setContentAreaFilled(false);
        BotonLimpiar.setBorderPainted(false);
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 90, 40));

        BotonRegreso1.setOpaque(false);
        BotonRegreso1.setContentAreaFilled(false);
        BotonRegreso1.setBorderPainted(false);
        BotonRegreso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegreso1ActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRegreso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 60, 50));
        jPanel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\favel\\OneDrive\\Documentos\\NetBeansProjects\\Proyecto-BDA\\Netbeans\\AgenciaFiscalPresentacion\\src\\main\\java\\Imagenes\\Pantalla_Registro.png")); // NOI18N
        jLabel8.setText(" ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistroActionPerformed
        // TODO add your handling code here:
        if (campoRFC.getText().isEmpty() || campoNombre.getText().isEmpty() || campoApellidoM.getText().isEmpty() || campoApellidoP.getText().isEmpty() || campoTelefono.getText().isEmpty() || fecha.getDate() == null || campoCurp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los espacios", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            // Encriptar el teléfono antes de agregar la persona
            String telefonoEncriptado = EncriptacionDatos.encriptar(campoTelefono.getText());

            // Guardando en un DTO
            PersonasDTO personaAgregar = new PersonasDTO(campoRFC.getText(), campoNombre.getText(), campoApellidoM.getText(), campoApellidoP.getText(), telefonoEncriptado, fecha.getDate(), campoCurp.getText());

            personaConsulta.registroPersona(personaAgregar);

            JOptionPane.showMessageDialog(this, "Persona agregada con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            campoRFC.setText("");
            campoApellidoM.setText("");
            campoApellidoP.setText("");
            campoCurp.setText("");
            campoNombre.setText("");
            campoTelefono.setText("");
            fecha.setDate(null);
        }

        control.desplegarMenu();
        dispose();
    }//GEN-LAST:event_BotonRegistroActionPerformed

    private void BotonRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistro1ActionPerformed
        // Verifica si los campos están vacíos
        if (campoRFC.getText().isEmpty() || campoNombre.getText().isEmpty() || campoApellidoM.getText().isEmpty()
                || campoApellidoP.getText().isEmpty() || campoTelefono.getText().isEmpty() || fecha.getDate() == null
                || campoCurp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            if(calcularEdad()>=18){
            String nombreSolicitante = campoNombre.getText() + " " + campoApellidoP.getText() + " " + campoApellidoM.getText();
            String rfc = campoRFC.getText();

            // Encriptar el teléfono antes de agregar la persona
            String telefonoEncriptado = EncriptacionDatos.encriptar(campoTelefono.getText());
            PersonasDTO personaAgregar = new PersonasDTO(campoRFC.getText(), campoNombre.getText(), campoApellidoM.getText(),
                    campoApellidoP.getText(),telefonoEncriptado, fecha.getDate(),
                    campoCurp.getText());

            personaConsulta.registroPersona(personaAgregar);

            JOptionPane.showMessageDialog(this, "Persona agregada con éxito", "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            control.desplegarDlgLicencia(nombreSolicitante, rfc);
            dispose();
            }else{
          JOptionPane.showMessageDialog(this, "No es posible realizar el registro, el solicitante es menor de edad", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BotonRegistro1ActionPerformed

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        // TODO add your handling code here:
        campoRFC.setText(" ");
        campoNombre.setText(" ");
        campoApellidoP.setText(" ");
        campoApellidoM.setText(" ");
        campoTelefono.setText(" ");
        fecha.setDate(null);
        campoCurp.setText(" ");
    }//GEN-LAST:event_BotonLimpiarActionPerformed
private int calcularEdad() {
        Date fechaSeleccionada = fecha.getDate();
        if (fechaSeleccionada != null) {
            LocalDate fechaNacimiento = fechaSeleccionada.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            LocalDate fechaActual = LocalDate.now();
            Period periodo = Period.between(fechaNacimiento, fechaActual);
            int edad = periodo.getYears();
           return edad;
        }else{
        return 0 ;
        }
}
    private void BotonRegreso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegreso1ActionPerformed
        // TODO add your handling code here:
        control.desplegarMenu();
        dispose();
    }//GEN-LAST:event_BotonRegreso1ActionPerformed

    private void campoTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoTelefonoKeyTyped
          if (campoTelefono.getText().length() >= 10) {
            evt.consume();
        }
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }

        if (campoTelefono.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_campoTelefonoKeyTyped

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped
        // TODO add your handling code here:
         final char keyChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(keyChar) || (keyChar == KeyEvent.VK_BACK_SPACE) || keyChar == KeyEvent.VK_DELETE)) {
            evt.consume();
        } 
    }//GEN-LAST:event_campoNombreKeyTyped

    private void campoApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoPKeyTyped
        // TODO add your handling code here:
         final char keyChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(keyChar) || (keyChar == KeyEvent.VK_BACK_SPACE) || keyChar == KeyEvent.VK_DELETE)) {
            evt.consume();
        } 
    }//GEN-LAST:event_campoApellidoPKeyTyped

    private void campoApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoMKeyTyped
        // TODO add your handling code here:
         final char keyChar = evt.getKeyChar();
        if (!(Character.isAlphabetic(keyChar) || (keyChar == KeyEvent.VK_BACK_SPACE) || keyChar == KeyEvent.VK_DELETE)) {
            evt.consume();
        } 
    }//GEN-LAST:event_campoApellidoMKeyTyped

    private void campoRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRFCKeyTyped
        // TODO add your handling code here:
         if (campoRFC.getText().length() >= 13) {
            evt.consume();
        }
    }//GEN-LAST:event_campoRFCKeyTyped

    private void campoCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCurpKeyTyped
        // TODO add your handling code here:
    char c = evt.getKeyChar();
    if(Character.isLowerCase(c)){//Todo lo que ingresa se pone em mayúscula
    String cad=(""+c).toUpperCase();
    c=cad.charAt(0);
    evt.setKeyChar(c);
    }
    }//GEN-LAST:event_campoCurpKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgRegistro dialog = new DlgRegistro(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonRegistro;
    private javax.swing.JButton BotonRegistro1;
    private javax.swing.JButton BotonRegreso1;
    private javax.swing.JTextField campoApellidoM;
    private javax.swing.JTextField campoApellidoP;
    private javax.swing.JTextField campoCurp;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoRFC;
    private javax.swing.JTextField campoTelefono;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
