/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package agenciafiscalpresentacion;

import Control.ControlPresentacion;
import consultas.ConsultasPlacas;
import dtos.LicenciaDTO;
import dtos.PlacasDTO;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author molin
 */
public class DlgReporte extends javax.swing.JDialog {

    ControlPresentacion control = new ControlPresentacion();

    /**
     * Creates new form DlgReporte
     */
    public DlgReporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DlgReporte() {
        initComponents();
        llenarTabla("Todos", null, null);
        this.setVisible(true);
    }

    public void llenarTabla(String tipoTramite, Date fechaDesde, Date fechaHasta) {
        List<LicenciaDTO> detallesLicencias = control.obtenerDetallesLicencias();
        List<PlacasDTO> detallesPlacas = control.obtenerDetallesPlacas();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpia la tabla antes de llenarla
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy"); // Formato de fecha

        if (tipoTramite.equals("Todos") || tipoTramite.equals("Licencias")) {
            for (LicenciaDTO licencia : detallesLicencias) {
                Date fechaRegistro = licencia.getFechaRegistro();
                if ((fechaDesde == null || fechaRegistro.after(fechaDesde)) && (fechaHasta == null || fechaRegistro.before(fechaHasta))) {
                    Object[] row = new Object[4];
                    row[0] = sdf.format(fechaRegistro); // Formatea la fecha
                    row[1] = "Licencia";
                    row[2] = licencia.getRFC();
                    row[3] = licencia.getCosto();
                    model.addRow(row);
                }
            }
        }

        if (tipoTramite.equals("Todos") || tipoTramite.equals("Placas")) {
            for (PlacasDTO placa : detallesPlacas) {
                Date fechaEmision = placa.getFechaEmision();
                if ((fechaDesde == null || fechaEmision.after(fechaDesde)) && (fechaHasta == null || fechaEmision.before(fechaHasta))) {
                    Object[] row = new Object[4];
                    row[0] = sdf.format(fechaEmision); // Formatea la fecha
                    row[1] = "Placas";
                    row[2] = placa.getAuto().getRfc();
                    row[3] = placa.getCosto();
                    model.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reporte = new javax.swing.JPanel();
        BotonRegreso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FechaDesde = new com.toedter.calendar.JDateChooser();
        FechaHasta = new com.toedter.calendar.JDateChooser();
        OpcionesTipoDeTramite = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonQuitarFiltros = new javax.swing.JButton();
        BotonFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTE");
        setPreferredSize(new java.awt.Dimension(698, 480));

        reporte.setBackground(new java.awt.Color(230, 243, 230));
        reporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonRegreso.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        BotonRegreso.setText("Volver");
        BotonRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresoActionPerformed(evt);
            }
        });
        reporte.add(BotonRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("VISUALIZACIÓN DE DATOS");
        reporte.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 340, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Tipo", "Solicitante", "Costo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        reporte.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 630, 170));
        reporte.add(FechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
        reporte.add(FechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        OpcionesTipoDeTramite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Licencias", "Placas" }));
        reporte.add(OpcionesTipoDeTramite, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel2.setText("Desde:                                Hasta:");
        reporte.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 190, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel3.setText("Filtrar por tipo");
        reporte.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 140, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel4.setText("Filtrar por fecha");
        reporte.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 140, 30));

        BotonQuitarFiltros.setText("Quitar filtros");
        BotonQuitarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonQuitarFiltrosActionPerformed(evt);
            }
        });
        reporte.add(BotonQuitarFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 110, -1));

        BotonFiltros.setText("Aplicar filtros");
        BotonFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFiltrosActionPerformed(evt);
            }
        });
        reporte.add(BotonFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresoActionPerformed
        // TODO add your handling code here:
        control.desplegarMenu();
        dispose();
    }//GEN-LAST:event_BotonRegresoActionPerformed

    private void BotonQuitarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonQuitarFiltrosActionPerformed
        llenarTabla("Todos", null, null);
    }//GEN-LAST:event_BotonQuitarFiltrosActionPerformed

    private void BotonFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFiltrosActionPerformed
        String tipoTramite = (String) OpcionesTipoDeTramite.getSelectedItem();
        Date fechaDesde = FechaDesde.getDate();
        Date fechaHasta = FechaHasta.getDate();
        llenarTabla(tipoTramite, fechaDesde, fechaHasta);
    }//GEN-LAST:event_BotonFiltrosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DlgReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DlgReporte dialog = new DlgReporte(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonFiltros;
    private javax.swing.JButton BotonQuitarFiltros;
    private javax.swing.JButton BotonRegreso;
    private com.toedter.calendar.JDateChooser FechaDesde;
    private com.toedter.calendar.JDateChooser FechaHasta;
    private javax.swing.JComboBox<String> OpcionesTipoDeTramite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel reporte;
    // End of variables declaration//GEN-END:variables
}
